### ISSUE TITLE
Day 1: Drum Kit challenge 

### ISSUE THREAD

**Issue by shubhamjaintech** [palashmon/JavaScript30#1]
If we keep on pressing the alphabet (i.e a,s,d,f,g etc)  for about 3-5 seconds then yellow background around the alphabet block/drum **sticks**  to the webpage  and do not get removed. i.e "playing" class gets removed when we release key  for short duration but if we keep on pressing the same key for longer period then playing class remain asitis inspite of remove class written correctly in script.

WHY is it so?

**Comment by palashmon** [comment]
I think this happens since when we keep pressing the down key for a long time the `transitionend` event is not called at all as the js code calls `playSound` function before the transition could actually finish. But on next `playSound` function calls there is no property changes at all as the `playing` class is still present. And since the `playing` class is already present the transition actually never starts in the subsequent function call and hence `transitionend` is also never called and hence `playing` class is never removed.

Also note as mentioned in [docs](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList):
> **add( String [, String] )**
> Add specified class values. If these classes already exist in attribute of the element, then they are ignored.

We can resolve this somehow by using [keyboard event repeat](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat) like:

``` js
if (!audio || e.repeat) return;
```

I hope this makes sense.

**Comment by palashmon** [comment]
Closing this issue now. Reopen if needed.
